version: '3.4'
services:
        db:
                image: mongo:4.4
                container_name: db
                ports:
                        - 27017:27017
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_ROOT_PASSWORD=123456
        api:
                build:
                        context: Demo_NET6_Mongodb_By_MongoFramework
                container_name: api
                ports:
                        - 9999:80               
                restart: always







